blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/rotn
    about: Feedback is greatly appreciated! If you have a suggestion, comment, or question for the pack, please put it in the discord!
  - name: GitHub Issues
    url: https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues
    about: Please check the existing issues here before submitting a bug report.
  - name: Trello Board
    url: https://trello.com/b/PZyYdW4A/rebirth-of-the-night
    about: Before making a suggestion, check our Trello for planned features and denied suggestions.
 
